#ifndef DEFINITIONS_HPP
#define DEFINITIONS_HPP

#define BLOCKSIZE 25
#define BORDERWIDTH 2
#define WINDOW_WIDTH 1000
#define WINDOW_HEIGHT 600
#define FIELD_SIZE 475
#define TIME_PER_ROUND 0.3f

#endif // DEFINITIONS_HPP
